### ISSUE TITLE
1.10 patch crash

### ISSUE THREAD

**Issue by kitsirota** [gamebooster/witcher3-booster#10]
I would love to contribute to this fix in any way I can.  It appears the 1.10 patch which shipped two days ago is breaking the game and the debug console on startup.

The error is as follows
![image](https://cloud.githubusercontent.com/assets/3009800/10409045/6da172dc-6edd-11e5-81c7-210b6cf752d6.png)

**Comment by skomski** [comment]
Updated binary release: https://github.com/gamebooster/witcher3-booster/releases/tag/0.4

Fixed in 8e9790bddcfca72fe2b0fee8d2d0982115e66829
Relevant code updates only in main.cc because the github windows  app messed up the two commits: https://github.com/gamebooster/witcher3-booster/commit/8e9790bddcfca72fe2b0fee8d2d0982115e66829#diff-d759577e53e2ce061239002d8a592cc5L311

**Comment by kitsirota** [comment]
@skomski Thanks for the quick response!!

It appears to be throwing the same error.  I confirmed the DLLs have been updated with the latest release (debug-console-enabler-patch-110.zip).

**Comment by skomski** [comment]
It definitely has a new error message in the update. Please post the updated error message.
Are you using the steam version?

**Comment by kitsirota** [comment]
Yep, using the steam version.

The error is:
Debug Console Mod Error
Pattern missmatch:
0 != 1 fyT

Thanks!

**Comment by skomski** [comment]
@kitsirota This can't be right. The current title is `Hook: MatchesCountCheckError`. You need to really replace your dlls with the ones from: https://github.com/gamebooster/witcher3-booster/releases/download/0.4/debug-console-enabler-patch-110.zip
